### ISSUE TITLE
Please consider placing this repository inside a 'Gutenberg' Github organization

### ISSUE THREAD

**Issue by jkoshy** [gbnewby/gutenbergsite#7]
Please consider placing official Gutenberg projects inside a 'Project Gutenberg' [Github organization](https://docs.github.com/en/github/setting-up-and-managing-organizations-and-teams/about-organizations).

Doing so would:

*   aid discoverability of the group of projects,
*   give a clear signal to users as to which source trees are 'official', and,
*    could ease management of developer access in the future.

**Comment by fredster33** [comment]
I agree. My 2 cents: if this current account is only being used for this repository (which it seems), GitHub has an option to convert the account to an organization.

**Comment by gbnewby** [comment]
Yes, that is the long-term plan. We are actually working on getting all of the books into github repos, not only the web pages.

We set it up privately initially during early development, and then shifted to public but in the same location. We will eventually promote this and other items to a top-level Gutenberg repository. Since we are still pursuing some major aspects of the work (not all of which are public), we prefer to not yet move this webpage repo to its "final" destination yet.

We appreciate this suggestion, and it is aligned with intentions.
