### ISSUE TITLE
Extra div ending tag in bookshelf

### ISSUE THREAD

**Issue by scompo** [gbnewby/gutenbergsite#9]
Hello,
in the page at https://www.gutenberg.org/ebooks/bookshelf/ there's an extra `</div>` tag visible as text near the end.

**Comment by gbnewby** [comment]
Fixed, along with other HTML issues. Thank you for reporting this.

**Comment by scompo** [comment]
I'm not able to see the site anymore, I live in italy, what's up with that?

**Comment by gbnewby** [comment]
The site is currently up, and we haven't had trouble reports.

There were reports of some areas of Italy being hijacked by law enforcement
there. If this happens, you would presumably get a message about it instead
of www.gutenberg.org .. we don't have any presence, personnel or activity
in Italy, so have no basis to address this.

If this doesn't explain what you are seeing, please let us know. You can
email help2021 AT pglaf.org rather than trying to use github as a support
forum, if you would like.
